version: '3.4'

services:
  nodejs-test:
    image: nodejs-test
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 80
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js